name: CimonPipe

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Who would win
        run: Nah I would

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Faily
        run: echo "Goodbye, World!"

