name: Release

on:
  push:
    tags:
      - 'v*'  # Läuft nur bei Tags wie v1.0.0, v1.1.0, etc.

permissions:
  contents: write  # Nötig für Release-Erstellung

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Anpassen auf Ihre Go-Version
    
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build binaries
      run: |
        mkdir -p releases
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o releases/cimon-windows-amd64.exe
        
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o releases/cimon-linux-amd64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o releases/cimon-linux-arm64
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o releases/cimon-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o releases/cimon-darwin-arm64
    
    - name: Create checksums
      run: |
        cd releases
        sha256sum * > checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          releases/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
